// GENERATED by Contents/tools/extensions.ts fingerprint (the rebuild runs it) -- do not edit.
// A fingerprint of diffusion-vendors.ts and the files of this extension it imports: a working copy records it, so a copy
// read by another version of this interpreter is not used. interpreter-code.test.ts checks it matches the sources.
export const INTERPRETER_CODE = "1aee6c2d49e5";
