// THE PAPERS THE DIFFUSION CODE IS BUILT ON -- one list, shown in the Diffusion module's Help & Acknowledgment (Ron,
// 2026-09-29: "We need the reference for what papers we used in the help message"). Each entry says what in the code
// rests on it. Versioned: an entry is added, never silently rewritten. Verified = the citation matches the publisher's record
// (Crossref, by DOI; Semantic Scholar where there is no DOI) or was read at its source
// during the work (2026-09-28/29); unverified entries are cited from memory and marked so, to check before release.

// v2 (2026-09-30): the two WMQL papers left with the WMQL code (Ron: "delete the wmql code"). v3: TractCloud and its atlas.
// v4 (2026-10-01, critic finding 11): dcm2niix's own citation; every entry checked against Crossref (Semantic Scholar
// for the CDMRI workshop paper, which has no DOI) -- Baumgartner et al. 2012's author list corrected, TractCloud cited
// by its pages (Crossref gives no volume).
// v5 (2026-10-01): CSD (Tournier 2007, Jeurissen 2014), its solver (Lawson & Hanson) and PTT (Aydogan & Shi 2021),
// checked against Crossref.
// v6 (2026-10-01): the UKF-near-tumors studies Yogesh Rathi pointed to (Chen 2015; Zhang 2017 ISBI) and their companions
// (Liao 2017, Gong 2018, O'Donnell 2017), checked against Crossref.
// v7 (2026-10-03): RapidParc (Bisten et al. 2026) names the tracts; TractCloud kept for its table.
// v8 (2026-10-04, critic finding 14): SynthStrip (Hoopes et al. 2022), the brain of tracking rule 3, checked against Crossref.
export const REFERENCES_VERSION = 8;

export interface Reference { cite: string; link?: string; usedFor: string; verified: boolean }

export const DIFFUSION_REFERENCES: Reference[] = [
  // How to cite the platform this follows.
  { cite: "Zhang F, Noh T, Juvekar P, Frisken SF, Rigolo L, Norton I, Kapur T, Pujol S, Wells W III, Yarmarkovich A, Kindlmann G, Wassermann D, San Jose Estepar R, Rathi Y, Kikinis R, Johnson HJ, Westin CF, Pieper S, Golby AJ, O'Donnell LJ. SlicerDMRI: Diffusion MRI and Tractography Research Software for Brain Cancer Surgery Planning and Visualization. JCO Clinical Cancer Informatics 4:299-309, 2020.", link: "https://ascopubs.org/doi/full/10.1200/CCI.19.00141", usedFor: "the clinical workflow (two-tensor UKF with free water near tumors) this module follows", verified: true },
  { cite: "Norton I, Ibn Essayed W, Zhang F, Pujol S, Yarmarkovich A, Golby AJ, Kindlmann G, Wassermann D, San Jose Estepar R, Rathi Y, Pieper S, Kikinis R, Johnson HJ, Westin CF, O'Donnell LJ. SlicerDMRI: Open Source Diffusion MRI Software for Brain Cancer Research. Cancer Research 77(21):e101-e103, 2017.", link: "https://aacrjournals.org/cancerres/article/77/21/e101/662618/", usedFor: "SlicerDMRI, the reference platform", verified: true },
  // UKF tractography.
  { cite: "Malcolm JG, Shenton ME, Rathi Y. Filtered multitensor tractography. IEEE Transactions on Medical Imaging 29(9):1664-1675, 2010.", link: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3045040/", usedFor: "UKF tractography (ukf.ts, ukf-gpu.ts): the two-tensor model and the unscented Kalman filter", verified: true },
  { cite: "Reddy CP, Rathi Y. Joint multi-fiber NODDI parameter estimation and tractography using the unscented information filter. Frontiers in Neuroscience 10:166, 2016.", link: "https://www.frontiersin.org/journals/neuroscience/articles/10.3389/fnins.2016.00166/full", usedFor: "the information form of the filter (ukf.ts)", verified: true },
  { cite: "Baumgartner C, Michailovich O, Levitt J, Pasternak O, Bouix S, Westin CF, Rathi Y. A unified tractography framework for comparing diffusion models on clinical scans. MICCAI Workshop on Computational Diffusion MRI (CDMRI), Nice, 2012.", usedFor: "free water inside the filter (ukf.ts)", verified: true },
  { cite: "UKFTractography, Brigham and Women's Hospital (github.com/pnlbwh/ukftractography), UKF Tractography Contribution and Software License Agreement.", link: "https://github.com/pnlbwh/ukftractography", usedFor: "the code ukf.ts is ported from", verified: true },
  // The tensor, maps, tracking.
  { cite: "Basser PJ, Mattiello J, LeBihan D. MR diffusion tensor spectroscopy and imaging. Biophysical Journal 66(1):259-267, 1994.", link: "https://doi.org/10.1016/S0006-3495(94)80775-1", usedFor: "the diffusion tensor (tensor.ts)", verified: true },
  { cite: "Salvador R, Peña A, Menon DK, Carpenter TA, Pickard JD, Bullmore ET. Formal characterization and extension of the linearized diffusion tensor model. Human Brain Mapping 24(2):144-155, 2005.", link: "https://doi.org/10.1002/hbm.20076", usedFor: "weighted least squares (tensor.ts)", verified: true },
  { cite: "Veraart J, Sijbers J, Sunaert S, Leemans A, Jeurissen B. Weighted linear least squares estimation of diffusion MRI parameters: strengths, limitations, and pitfalls. NeuroImage 81:335-346, 2013.", link: "https://doi.org/10.1016/j.neuroimage.2013.05.028", usedFor: "weighted least squares (tensor.ts)", verified: true },
  { cite: "Pajevic S, Pierpaoli C. Color schemes to represent the orientation of anisotropic tissues from diffusion tensor data: application to white matter fiber tract mapping in the human brain. Magnetic Resonance in Medicine 42(3):526-540, 1999.", link: "https://doi.org/10.1002/(SICI)1522-2594(199909)42:3<526::AID-MRM15>3.0.CO;2-J", usedFor: "color FA (tensor.ts)", verified: true },
  { cite: "Basser PJ, Pajevic S, Pierpaoli C, Duda J, Aldroubi A. In vivo fiber tractography using DT-MRI data. Magnetic Resonance in Medicine 44(4):625-632, 2000.", link: "https://doi.org/10.1002/1522-2594(200010)44:4<625::AID-MRM17>3.0.CO;2-O", usedFor: "single-tensor streamline tracking (tracking.ts)", verified: true },
  { cite: "Otsu N. A threshold selection method from gray-level histograms. IEEE Transactions on Systems, Man, and Cybernetics 9(1):62-66, 1979.", link: "https://doi.org/10.1109/TSMC.1979.4310076", usedFor: "the brain mask (tensor.ts brainMask)", verified: true },
  { cite: "Hoopes A, Mora JS, Dalca AV, Fischl B, Hoffmann M. SynthStrip: skull-stripping for any brain image. NeuroImage 260:119474, 2022.", link: "https://doi.org/10.1016/j.neuroimage.2022.119474", usedFor: "the brain the whole-brain tracking starts and stops in (tracking rule 3), found on the MRI of the anatomy by the segmentation server (haversack)", verified: true },
  { cite: "Garyfallidis E, Brett M, Amirbekian B, et al. Dipy, a library for the analysis of diffusion MRI data. Frontiers in Neuroinformatics 8:8, 2014.", link: "https://doi.org/10.3389/fninf.2014.00008", usedFor: "the independent check of the tensor fit (a check tool, not a dependency)", verified: true },
  // Distortion correction.
  { cite: "Chang H, Fitzpatrick JM. A technique for accurate magnetic resonance imaging in the presence of field inhomogeneities. IEEE Transactions on Medical Imaging 11(3):319-329, 1992.", link: "https://doi.org/10.1109/42.158935", usedFor: "the reversed phase-encoding principle (distortion.ts)", verified: true },
  { cite: "Ruthotto L, Kugel H, Olesch J, Fischer B, Modersitzki J, Burger M, Wolters CH. Diffeomorphic susceptibility artifact correction of diffusion-weighted magnetic resonance images. Physics in Medicine and Biology 57(18):5715-5731, 2012.", link: "https://iopscience.iop.org/article/10.1088/0031-9155/57/18/5715", usedFor: "the variational model with the Jacobian barrier (distortion.ts)", verified: true },
  { cite: "Macdonald J, Ruthotto L. Improved susceptibility artifact correction of echo-planar MRI using the alternating direction method of multipliers. Journal of Mathematical Imaging and Vision, 2018. arXiv:1607.00531.", link: "https://arxiv.org/abs/1607.00531", usedFor: "the full formulation, solver and parameters implemented (distortion.ts)", verified: true },
  // Reading the scan: the second opinion.
  { cite: "Li X, Morgan PS, Ashburner J, Smith J, Rorden C. The first step for neuroimaging data analysis: DICOM to NIfTI conversion. J Neurosci Methods 264:47-56, 2016.", link: "https://doi.org/10.1016/j.jneumeth.2016.03.001", usedFor: "dcm2niix, run on every diffusion scan from the database as a second opinion (vendor/dcm2niix/)", verified: true },
  // Fiber distributions and parallel transport tracking (csd.ts, responses.ts, ptt.ts; checked in the case library, not
  // yet in the module's buttons).
  { cite: "Tournier JD, Calamante F, Connelly A. Robust determination of the fibre orientation distribution in diffusion MRI: non-negativity constrained super-resolved spherical deconvolution. NeuroImage 35(4):1459-1472, 2007.", link: "https://doi.org/10.1016/j.neuroimage.2007.02.016", usedFor: "constrained spherical deconvolution: the fiber distribution kept non-negative (csd.ts)", verified: true },
  { cite: "Jeurissen B, Tournier JD, Dhollander T, Connelly A, Sijbers J. Multi-tissue constrained spherical deconvolution for improved analysis of multi-shell diffusion MRI data. NeuroImage 103:411-426, 2014.", link: "https://doi.org/10.1016/j.neuroimage.2014.07.061", usedFor: "multi-shell, multi-tissue CSD: white matter, gray matter and fluid from every shell (csd.ts, responses.ts)", verified: true },
  { cite: "Lawson CL, Hanson RJ. Solving Least Squares Problems. Prentice-Hall, 1974 (SIAM Classics in Applied Mathematics, 1995).", link: "https://doi.org/10.1137/1.9781611971217", usedFor: "the exact solver: non-negative least squares on the CSD problem's dual (csd.ts)", verified: true },
  { cite: "Aydogan DB, Shi Y. Parallel transport tractography. IEEE Transactions on Medical Imaging 40(2):635-647, 2021.", link: "https://doi.org/10.1109/TMI.2020.3034038", usedFor: "parallel transport tractography (ptt.ts)", verified: true },
  // Naming tracts.
  { cite: "Bisten J, von Bornhaupt V, Grün J, Bauer T, Rüber T, Schultz T. RapidParc: A global-context transformer for parallel, accurate, and lesion-robust tractogram parcellation. Imaging Neuroscience 4, 2026.", link: "https://doi.org/10.1162/IMAG.a.1168", usedFor: "RapidParc: the network that names the tracts since 2026-10-03, and its trained weights (rapidparc/)", verified: true },
  { cite: "Xue T, Chen Y, Zhang C, Golby AJ, Makris N, Rathi Y, Cai W, Zhang F, O'Donnell LJ. TractCloud: registration-free tractography parcellation with a novel local-global streamline point cloud representation. MICCAI 2023, Lecture Notes in Computer Science, pp. 409-419.", link: "https://doi.org/10.1007/978-3-031-43993-3_40", usedFor: "TractCloud: the tract-naming network until 2026-10-03; its table of clusters, tracts and names is still the one used (tractcloud/)", verified: true },
  { cite: "Zhang F, Wu Y, Norton I, Rigolo L, Rathi Y, Makris N, O'Donnell LJ. An anatomically curated fiber clustering white matter atlas for consistent white matter tract parcellation across the lifespan. NeuroImage 179:429-447, 2018.", link: "https://doi.org/10.1016/j.neuroimage.2018.06.027", usedFor: "the atlas of 800 fiber clusters the tract names come from (RapidParc and TractCloud were both trained on it)", verified: true },
  // Data.
  { cite: "Aerts H, Schirner M, Jeurissen B, Van Roost D, Achten E, Ritter P, Marinazzo D. Modeling brain dynamics in brain tumor patients using The Virtual Brain. eNeuro 5(3):ENEURO.0083-18.2018, 2018. Data: OpenNeuro ds001226 (CC0).", link: "https://openneuro.org/datasets/ds001226", usedFor: "the development and test cases", verified: true },
  { cite: "Chen Z, Tie Y, Olubiyi O, Rigolo L, Mehrtash A, Norton I, Pasternak O, Rathi Y, Golby AJ, O'Donnell LJ. Reconstruction of the arcuate fasciculus for surgical planning in the setting of peritumoral edema using two-tensor unscented Kalman filter tractography. NeuroImage: Clinical 7:815-822, 2015.", link: "https://doi.org/10.1016/j.nicl.2015.03.009", usedFor: "two-tensor UKF tracking through peritumoral edema (10 patients; the arcuate fasciculus traced where single-tensor tracking broke)", verified: true },
  { cite: "Liao R, Ning L, Chen Z, Rigolo L, Gong S, Pasternak O, Golby AJ, Rathi Y, O'Donnell LJ. Performance of unscented Kalman filter tractography in edema: Analysis of the two-tensor model. NeuroImage: Clinical 15:819-831, 2017.", link: "https://doi.org/10.1016/j.nicl.2017.06.027", usedFor: "how UKF's seeding and stopping settings and the free-water model change tracking in edema", verified: true },
  { cite: "Gong S, Zhang F, Norton I, Essayed WI, Unadkat P, Rigolo L, Pasternak O, Rathi Y, Hou L, Golby AJ, O'Donnell LJ. Free water modeling of peritumoral edema using multi-fiber tractography: Application to tracking the arcuate fasciculus for neurosurgical planning. PLOS ONE 13(5):e0197056, 2018.", link: "https://doi.org/10.1371/journal.pone.0197056", usedFor: "free water on by default near tumors (26 patients; larger arcuate fasciculus where it crosses edema)", verified: true },
  { cite: "O'Donnell LJ, Suter Y, Rigolo L, Kahali P, Zhang F, Norton I, Albi A, Olubiyi O, Meola A, Essayed WI, Unadkat P, Ciris PA, Wells WM, Rathi Y, Westin CF, Golby AJ. Automated white matter fiber tract identification in patients with brain tumors. NeuroImage: Clinical 13:138-153, 2017.", link: "https://doi.org/10.1016/j.nicl.2016.11.023", usedFor: "naming tracts in tumor patients with an atlas learned from healthy brains (18 patients, checked against functional MRI)", verified: true },
  { cite: "Zhang F, Kahali P, Suter Y, Norton I, Rigolo L, Savadjiev P, Song Y, Rathi Y, Cai W, Wells WM, Golby AJ, O'Donnell LJ. Automated connectivity-based groupwise cortical atlas generation: Application to data of neurosurgical patients with brain tumors for cortical parcellation prediction. IEEE ISBI 2017:774-777.", link: "https://doi.org/10.1109/ISBI.2017.7950633", usedFor: "background: where tracts end on the cortex in tumor patients (not used in the code yet)", verified: true },
];

/** The list as plain text lines for a help panel. */
export function referencesText(): string[] {
  return DIFFUSION_REFERENCES.map((r, i) => `${i + 1}. ${r.cite}${r.link ? ` ${r.link}` : ""} — ${r.usedFor}${r.verified ? "" : " (citation to be checked)"}`);
}
